name: Build

on:
  push:
    branches:
      - "main"

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: tiny-creatures

jobs:
  linux-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux-x86_64
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux-x86_64/$EXPORT_NAME"
      - name: Create archive
        run: tar -czvf linux-x86_64.tar.xz build/linux-x86_64
      - name: Publish
        id: Publish-Linux
        uses: softprops/action-gh-release@v1
        with:
          name: tiny-creatures
          tag_name: v0.1.0
          body_path: CHANGELOG.md
          token: ${{ secrets.CI_TOKEN }}
          files: |
            linux-x86_64.tar.xz
  
  windows-build:
    name: Windows Build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows-x86_64
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows-x86_64/$EXPORT_NAME.exe"
      - name: Create archive
        run: zip windows-x86_64 build/windows-x86_64 -l
      - name: Publish
        id: Publish-Windows
        uses: softprops/action-gh-release@v1
        with:
          name: tiny-creatures
          tag_name: v0.1.0
          body_path: CHANGELOG.md
          token: ${{ secrets.CI_TOKEN }}
          files: |
            windows-x86_64.tar.xz

  web-build:
    name: Web Build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Create archive
        run: tar -czvf web.tar.xz build/web
      - name: Publish
        id: Publish-Web
        uses: softprops/action-gh-release@v1
        with:
          name: tiny-creatures
          tag_name: v0.1.0
          body_path: CHANGELOG.md
          token: ${{ secrets.CI_TOKEN }}
          files: |
            web.tar.xz